title: Nonsense Generator
description: Documentazione del progetto universitario
font:
  family: "Nunito Sans, sans-serif"
  url: "https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap"
baseurl: "/NONSENSE-generator"
